# Тут будут мои настройки

[manager]
sort_by             = "natural"             # Как алфавит, но не "1 < 10 < 2", а "1 < 2 < 10"
sort_dir_first      = true                  # Чтоб директории были первыми, не смотря на сортировку
#show_hidden         = true                  # Показывать скрытые файлы. Спорно, потому что они первые в списке, бесит. Мб проще бинд юзать
